### PR TITLE
Fix "TypeError: object is not a function" at `var m = r(url)`

### PR DESCRIPTION
**Pull request by ikr**

### CODE REVIEW

**Comment by dominictarr** [comment]
thanks.

**Comment by mridgway** [comment]
This fix does not appear to have made it into an npm release. Can someone publish this to npm?

**Comment by dominictarr** [comment]
I just installed proxy-by-url from npm and got exactly the same code as is here.

**Comment by mridgway** [comment]
I've installed from two different machines and received the old code. Are you sure you do not have it cached in your local npm? I haven't used this library before, so it's not cached for me.

npm info:

```
{ name: 'proxy-by-url',
  description: 'custom logic for node-http-proxy to proxy basedon incoming url',
  'dist-tags': { latest: '0.0.1' },
  versions: [ '0.0.0', '0.0.1' ],
  maintainers: 'dominictarr <dominic.tarr@gmail.com>',
  time: 
   { '0.0.0': '2011-07-30T09:55:29.217Z',
     '0.0.1': '2011-08-09T04:29:31.417Z' },
  author: 'Dominic Tarr <dominic.tarr@gmail.com> (http://bit.ly/dominictarr)',
  repository: 
   { type: 'git',
     url: 'git://github.com/dominictarr/proxy-by-url.git' },
  version: '0.0.1',
  homepage: 'http://github.com/dominictarr/proxy-by-url',
  dependencies: {},
  devDependencies: {},
  scripts: { test: 'meta-test test/*.js' },
  engines: { node: '*' },
  dist: 
   { shasum: 'bfd69ec794696b3071e1febabf43ec852d2c6508',
     tarball: 'http://registry.npmjs.org/proxy-by-url/-/proxy-by-url-0.0.1.tgz' },
  directories: {} }
```

**Comment by dominictarr** [comment]
what version did you get?

0.0.1?
that is the newest.

**Comment by mridgway** [comment]
Yes, 0.0.1. According to `npm info`, 0.0.1 was released before this issue was closed.

**Comment by dominictarr** [comment]
when I diff the code I checked out of the repo, and the code I installed
from npm,

```
 diff proxy-by-url/index.js experiments/node_modules/proxy-by-url/index.js
```

I get no changes.

**Comment by matthewhadley** [comment]
on a fresh install of proxy-by-url

```
npm i proxy-by-url
```

I am seeing line 16, index.js:

```
var m = r(url)
```

**Comment by dominictarr** [comment]
you must have edited the code,
I am seeing that line at 10, in both a fresh npm install and a git checkout.
try installing from the git clone address and see if that works the same.

npm install git:...

**Comment by mridgway** [comment]
@dominictarr How would it be possible for this code to be in an npm release if the latest npm release was _before_ this code change? Your `npm install` is probably working because you have it `npm link`ed locally already.

**Comment by matthewhadley** [comment]
I've not edited any code. Can you please try:

```
npm cache clear
```

Then do the npm install again.

**Pull request merged**
